version: "3"
services:
  pg:
    # image: postgres:12.1-alpine
    build:
      context: ./pg14
      dockerfile: Dockerfile
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: test
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./call_log.db:/tmp/call_log.db
    networks:
      - pgtest_network
  grafana:
    image: grafana/grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: postgres:5433
      GF_DATABASE_NAME: test
      GF_DATABASE_USER: postgres
      GF_DATABASE_PASSWORD: postgres
    ports:
      - "3000:3000"
    depends_on:
      - pg
    networks:
      - pgtest_network
networks:
  pgtest_network:
    driver: bridge
